### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Cp-022** [VirtualWiFi/VirtualWifi#6]
Typos in license

**Comment by Cp-022** [comment]
[Here](http://imgur.com/GfyS795

**Comment by Sadusko** [comment]
Where do you see a typo?

**Comment by Sadusko** [comment]
Ah nevermind, I see it.

Good eyes.

**Comment by Cp-022** [comment]
xD got bored yesterday decided to read a license and so I found it.

**Comment by Sadusko** [comment]
Seems like it lol. 
Fixed it just now :+1:
